[pytest]
addopts = [
  "--reruns=2",
  "--only-rerun=aiohttp.client_exceptions.ClientConnectorError",
  "--only-rerun=aiohttp.client_exceptions.ConnectionTimeoutError",
]
asyncio_mode = "auto"
strict = true
